---
- name: Install Apache2
  hosts: localhost
  # become: true
  tasks: 
    - name: Install Apache2
      apt:
        name: apache2
        state: present
      when: ansible_distribution == 'Ubuntu'
    - name: Install Apache httpd server on macOS
      homebrew:
        name: httpd
        state: present 
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] == "arm64"

    - name: Install httpd on CentOS Machines
      yum:
        name: httpd
        state: present
      when: ansible_distribution == 'CentOS'
    - name: Start Apache service on macOS
      command: sudo apachectl start
      become: yes
      when: ansible_facts['os_family'] == "Darwin" and ansible_facts['architecture'] == "arm64"

